Update manifest.json
Fix below error by adding the property
org.springframework.beans.FatalBeanException: Context hybris Global Context Factory  couldn't  be created correctly due to, Invalid bean definition with name 'sapCpiProductFeaturePersistenceHook' defined in class path resource [sapcpiproductexchange-spring.xml]: Could not resolve placeholder 'sapcpiproductexchange.sapCpiProductFeaturePersistenceHook.collectionDelimiter' in value "${sapcpiproductexchange.sapCpiProductFeaturePersistenceHook.collectionDelimiter}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'sapcpiproductexchange.sapCpiProductFeaturePersistenceHook.collectionDelimiter' in value "${sapcpiproductexchange.sapCpiProductFeaturePersistenceHook.collectionDelimiter}"